### ISSUE TITLE
Fälschlicherweise Pt. 6 (Apo) nach ABBR in EM

### ISSUE THREAD

**Issue by mixa72** [sbsdev/dtbook2sbsform#14]
Der einst abgeschlossene Bugfix unter http://redmine.sbszh.ch/issues/2243 funktioniert nicht mehr. Wahrscheinlich durch die Anpassungen 2018/2019. D.h.

````
<p><em>es lebe das Format <abbr>A</abbr>4</em></p>
````

wird wieder falsch übersetzt, nämlich

````
 __% LBE D F?MAT >A'#D'.  
````

Die Beispiele (mit und ohne em) unbedingt in die Tests aufnehmen und den Bug beheben. Eilt nicht, da nicht sehr häufig auftretend.

**Comment by egli** [comment]
So if I understand correctly we want
```
 __% LBE D F?MAT >A#D'.
```  
 @mixa72 Correct?

**Comment by mixa72** [comment]
Correct!
