### ISSUE TITLE
non-breaking space for braille

### ISSUE THREAD

**Issue by egli** [sbsdev/dtbook2sbsform#16]
Analog zur nbsp-Entity, die momentan nur für den Grossdruck reserviert ist, wäre es sinnvoll, ein weiteres Zeichen zu definieren, welches das Gleiche für die Braille-Ausgabe leistet. Natürlich könnte man auch dasselbe Zeichen verwenden, d.h. nbsp (#x00A0) sowohl für GD als auch Braille. Da die im File verwendeten Entities aber ohnehin jeweils nach der XML-Deklaration definiert sind, macht es Sinn, dass LibLouis lediglich die Funktionalität für eine festes Leerzeichen in Braille anbietet. Der Übertragende kann dann selbst entscheiden, ob er NBSP als brl:select definiert (d.h. für GD/EB UND Braille) oder für Braille eine eigene Entity verwenden möchte.

## Ziele:

- Im Braille-File muss das feste Leerzeichen als "b" zwischen 2 Wörtern erscheinen, z.B. DR.bHUGENTOBLER
- Die Wörter links und rechts des festen Leerzeichens müssen beide als Einzeleinträge im Dictionary erscheinen und korrigierbar sein (d.h. die Übersetzung muss durch eine word-Regel steuerbar sein)

## ToDo:

1. Definition eines Spezialzeichens (z.B. ▅) in sbs-special.ch mit virtuellen Punkten z.B.
```
# NBSP BRAILLE
space  \x2585 bd
```
2. Zusätzlicher Eintrag in sbs.dis
```
display  b bd
```

Mit den Schritten 1. und 2. erhält man das gewünschte Resultat:

Eingabe:
```
 vordurchprobe▅protuberanzakte
```
Ausgabe:
```
 ,?,4PROBEbQTUB7+ZAK(
```
Die Übersetzungen der Wörter 'vordurchprobe' und 'protuberanzakte' sind durch entspr. word-Regeln steuerbar (getestet mit LibLouis 3.16.1).

Letzter Schritt: Das zuvor definierte Zeichen (▅) muss VOR dem eruieren unbekannter Wörter durch ein richtiges Leerzeichen ersetzt werden, damit aus dem konkatenierten String "vordurchprobe▅protuberanzakte" die beiden Einzelwörter erkannt werden.

Das Zeichen (▅) kann nun im File frei verwendet oder als Entity definiert werden.

**Comment by mixa72** [comment]
getestet am 08.09.2023 -> funktioniert (inkl. WB / Trennungen)

**Comment by mixa72** [comment]
getestet am 22.09.2023 (prod) -> funktioniert (inkl. WB / Trennungen)

**Comment by mixa72** [comment]
erledigt

**Comment by mixa72** [comment]
closed
